### ISSUE TITLE
[PE-D][Tester C] slashes in name not allowed 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-F12-1/tp#204]
![image.png](https://raw.githubusercontent.com/junlee1991/ped/main/files/e238bac0-b59d-4079-9f9b-c30c148d952c.png)

If a doctor has a "/" in his name, it cannot be added into the app. 

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: junlee1991/ped#2

**Comment by praveenkrishna0512** [comment]
Thanks for the note

@owen-yap @vigonometry I leave this to either of you to deconflict -- I believe this would come under the attributes constraints for patients and doctors

**Comment by vigonometry** [comment]
Closed by #260
