### ISSUE TITLE
[PE-D][Tester D] Input validation for find commands are not implemented. 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-F12-1/tp#210]
For the add command, I can add weight and height, and they are both validated. However, for the find command, it is not validated. 

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: wxxedu/ped#9

**Comment by vigonometry** [comment]
Added under the planned enhancements section of the Developer Guide (Appendix A).
Tagging issue as resolved @owen-yap @praveenkrishna0512
