### ISSUE TITLE
[PE-D][Tester D] In the UserGuide, does not explain what each parameter is for. 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-F12-1/tp#214]
As described. 

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: wxxedu/ped#11

**Comment by vigonometry** [comment]
Unclear on what parameters they imply. Requires more information since parameters along with words are specified under every command.

**Comment by praveenkrishna0512** [comment]
@vigonometry has completed this in UG
