### ISSUE TITLE
[PE-D][Tester B] Phone number field has no digit limit.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-F12-1/tp#215]
I am able to input phone numbers way longer than any existing phone number in the world. A validation check for this field would be nice.

![image.png](https://raw.githubusercontent.com/Yaladah/ped/main/files/baf16d7c-0b7f-4ff2-b31c-f06437b48018.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: Yaladah/ped#8

**Comment by vigonometry** [comment]
Valid feature flaw but won't fix
