### ISSUE TITLE
[PE-D][Tester A] Patient list or doctor list when adding doctor or patient respectively

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-F12-1/tp#216]
When adding a new doctor, the patient list suddenly vanishes.

Here is the resultant screen for adding a new doctor:

![Bug 6.PNG](https://raw.githubusercontent.com/FireRadical22/ped/main/files/a65fa94b-4762-4530-89f9-d33059f01cb5.PNG)

vs before adding a new doctor:

![Bug 10.PNG](https://raw.githubusercontent.com/FireRadical22/ped/main/files/03435e35-4694-4ce8-a17c-784fc2882c53.PNG)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: FireRadical22/ped#3

**Comment by owen-yap** [comment]
The screenshots here show adding a new patient and not a new doctor.

**Comment by vigonometry** [comment]
User Guide will be updated to explain this (we display only the doctors/patients relevant to the patients/doctors by filtering the view). `list-doc` and `list-ptn` will result in normal functionality.

Related issues: #225 #222 #221
