### ISSUE TITLE
[PE-D][Tester A] Image given in add-doc command does not match what is displayed on Docedex

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-F12-1/tp#225]
Image given in add-doc command section does not have the selected doctor/patient panel, which is present in docedex. This image is also used in step 2 in Docedex Tutorial section.

![image.png](https://raw.githubusercontent.com/FireRadical22/ped/main/files/c38474ff-9b13-474d-86f4-3802aa280e24.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: FireRadical22/ped#11

**Comment by vigonometry** [comment]
Screenshots in the UserGuide will be updated to match current state of product

**Comment by vigonometry** [comment]
Resolved
