### ISSUE TITLE
Update UG

### ISSUE THREAD

**Issue by praveenkrishna0512** [AY2223S2-CS2103T-F12-1/tp#9]
User Guide
- Move the draft UG content into the User Guide page

**Comment by owen-yap** [comment]
@vigonometry 
![image](https://user-images.githubusercontent.com/69426017/222881925-ea28b370-7f5f-495c-ba8c-d37e1a3aa22a.png)
![image](https://user-images.githubusercontent.com/69426017/222881944-d5da2a4d-4a66-4ce6-a698-770dc98532e3.png)
